[0m[[0m[31merror[0m] [0m[0msttp.client3.SttpClientException$ConnectException: Exception when sending request: GET :[0m
[0m[[0m[31merror[0m] [0m[0m	at sttp.client3.SttpClientException$.defaultExceptionToSttpClientException(SttpClientException.scala:37)[0m
[0m[[0m[31merror[0m] [0m[0m	at sttp.client3.HttpURLConnectionBackend.$anonfun$adjustExceptions$1(HttpURLConnectionBackend.scala:296)[0m
[0m[[0m[31merror[0m] [0m[0m	at sttp.client3.SttpClientException$$anonfun$adjustExceptions$1.applyOrElse(SttpClientException.scala:59)[0m
[0m[[0m[31merror[0m] [0m[0m	at sttp.client3.SttpClientException$$anonfun$adjustExceptions$1.applyOrElse(SttpClientException.scala:58)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)[0m
[0m[[0m[31merror[0m] [0m[0m	at sttp.monad.MonadError.handleError(MonadError.scala:26)[0m
[0m[[0m[31merror[0m] [0m[0m	at sttp.monad.MonadError.handleError$(MonadError.scala:23)[0m
[0m[[0m[31merror[0m] [0m[0m	at sttp.client3.monad.IdMonad$.handleError(IdMonad.scala:6)[0m
[0m[[0m[31merror[0m] [0m[0m	at sttp.client3.SttpClientException$.adjustExceptions(SttpClientException.scala:58)[0m
[0m[[0m[31merror[0m] [0m[0m	at sttp.client3.HttpURLConnectionBackend.adjustExceptions(HttpURLConnectionBackend.scala:296)[0m
[0m[[0m[31merror[0m] [0m[0m	at sttp.client3.HttpURLConnectionBackend.send(HttpURLConnectionBackend.scala:30)[0m
[0m[[0m[31merror[0m] [0m[0m	at sttp.client3.HttpURLConnectionBackend.send(HttpURLConnectionBackend.scala:22)[0m
[0m[[0m[31merror[0m] [0m[0m	at sttp.client3.FollowRedirectsBackend.sendWithCounter(FollowRedirectsBackend.scala:29)[0m
[0m[[0m[31merror[0m] [0m[0m	at sttp.client3.FollowRedirectsBackend.send(FollowRedirectsBackend.scala:24)[0m
[0m[[0m[31merror[0m] [0m[0m	at sttp.client3.RequestT.send(RequestT.scala:321)[0m
[0m[[0m[31merror[0m] [0m[0m	at RestClient$.main(RestClient.scala:27)[0m
[0m[[0m[31merror[0m] [0m[0m	at RestClient.main(RestClient.scala)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.reflect.Method.invoke(Method.java:566)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.invokeMain(Run.scala:143)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.execute$1(Run.scala:93)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:120)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run$.executeSuccess(Run.scala:186)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.runWithLoader(Run.scala:120)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:1983)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1922)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.util.Try$.apply(Try.scala:213)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:369)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.Thread.run(Thread.java:829)[0m
[0m[[0m[31merror[0m] [0m[0mCaused by: java.net.MalformedURLException: no protocol: :[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.net.URL.<init>(URL.java:645)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.net.URL.<init>(URL.java:541)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.net.URL.<init>(URL.java:488)[0m
[0m[[0m[31merror[0m] [0m[0m	at sttp.client3.HttpURLConnectionBackend$.$anonfun$apply$default$3$1(HttpURLConnectionBackend.scala:314)[0m
[0m[[0m[31merror[0m] [0m[0m	at sttp.client3.HttpURLConnectionBackend.openConnection(HttpURLConnectionBackend.scala:69)[0m
[0m[[0m[31merror[0m] [0m[0m	at sttp.client3.HttpURLConnectionBackend.$anonfun$send$1(HttpURLConnectionBackend.scala:31)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.util.Try$.apply(Try.scala:210)[0m
[0m[[0m[31merror[0m] [0m[0m	at sttp.monad.MonadError.handleError(MonadError.scala:24)[0m
[0m[[0m[31merror[0m] [0m[0m	at sttp.monad.MonadError.handleError$(MonadError.scala:23)[0m
[0m[[0m[31merror[0m] [0m[0m	at sttp.client3.monad.IdMonad$.handleError(IdMonad.scala:6)[0m
[0m[[0m[31merror[0m] [0m[0m	at sttp.client3.SttpClientException$.adjustExceptions(SttpClientException.scala:58)[0m
[0m[[0m[31merror[0m] [0m[0m	at sttp.client3.HttpURLConnectionBackend.adjustExceptions(HttpURLConnectionBackend.scala:296)[0m
[0m[[0m[31merror[0m] [0m[0m	at sttp.client3.HttpURLConnectionBackend.send(HttpURLConnectionBackend.scala:30)[0m
[0m[[0m[31merror[0m] [0m[0m	at sttp.client3.HttpURLConnectionBackend.send(HttpURLConnectionBackend.scala:22)[0m
[0m[[0m[31merror[0m] [0m[0m	at sttp.client3.FollowRedirectsBackend.sendWithCounter(FollowRedirectsBackend.scala:29)[0m
[0m[[0m[31merror[0m] [0m[0m	at sttp.client3.FollowRedirectsBackend.send(FollowRedirectsBackend.scala:24)[0m
[0m[[0m[31merror[0m] [0m[0m	at sttp.client3.RequestT.send(RequestT.scala:321)[0m
[0m[[0m[31merror[0m] [0m[0m	at RestClient$.main(RestClient.scala:27)[0m
[0m[[0m[31merror[0m] [0m[0m	at RestClient.main(RestClient.scala)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.reflect.Method.invoke(Method.java:566)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.invokeMain(Run.scala:143)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.execute$1(Run.scala:93)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:120)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run$.executeSuccess(Run.scala:186)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.runWithLoader(Run.scala:120)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:1983)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1922)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.util.Try$.apply(Try.scala:213)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:369)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.Thread.run(Thread.java:829)[0m
[0m[[0m[31merror[0m] [0m[0m(Compile / [31mrun[0m) sttp.client3.SttpClientException$ConnectException: Exception when sending request: GET :[0m
